/**
 * The generated agent file behind kimi's `--tools none`.
 *
 * Kimi 0.31.1 has no tool-removal flag, but an agent definition's frontmatter
 * carries the profile's tool allowlist: `tools` accepts a comma-separated
 * string or a list, `["*"]` means unrestricted, and an explicit empty list is
 * the file's own set (embedded `packages/agent-core/src/profile/agentfile/
 * parser.ts` and `from-file.ts` in the 0.31.1 binary; the flag is
 * `--agent-file <path>`, "Load an agent definition from a Markdown file",
 * 0.31.1 `--help`). The profile's tools reach the tool manager verbatim:
 * setActiveTools puts them in a set of enabled exact names plus MCP access
 * patterns, and both gates are strict membership tests, so an empty list
 * enables no built-in and no MCP tool, and get loopTools derives from the
 * same sets (agent/tools ToolManager). A profile renderer even prints the
 * state as "Tools: none", distinct from an unset list's "Tools: all". The
 * manager registers builtins regardless, but registration is not exposure:
 * only loopTools reach the model.
 *
 * An agent file must carry a non-empty prompt body, and that body becomes the
 * profile's system prompt. Codemux therefore writes exactly `${base_prompt}`,
 * which both engines define as the effective default profile's own prompt for
 * an explicit --agent-file (v1 `entryFromDefinition`, v2
 * ExplicitAgentProfileLoaderService), so the run keeps kimi's base
 * instructions, and everything else in the definition is left unset.
 *
 * The file lives under the real brand home in `.codemux/`, a directory no
 * discovery scans (user agents come from `<brand home>/agents` and
 * `~/.agents/agents`, skills from `<brand home>/skills`, embedded `roots.ts`
 * conventions at 0.31.1) and one scode keeps reachable as harness state;
 * never under the temp root, whose Linux sandbox mount would hide it. The
 * capability stays unclaimed until the live probe runs: kimi hit its weekly
 * usage limit on 2026-09-17, so no model request was possible (see
 * docs/HERMETIC.md).
 */

import { randomBytes } from "node:crypto";
import {
  lstatSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

export interface KimiNoToolsFile {
  /** The path to pass as `--agent-file`. */
  path: string;
  /** Removes the file. */
  finalize: () => void;
}

const PARENT_DIR_NAME = ".codemux";
const FILE_PREFIX = "no-tools-";

const AGENT_FILE_TEXT = [
  "---",
  "name: codemux-no-tools",
  "description: Tools-free profile generated by codemux; keeps the default prompt.",
  "tools: []",
  "---",
  "",
  "${base_prompt}",
  "",
].join("\n");

function processAlive(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    return (error as NodeJS.ErrnoException).code !== "ESRCH";
  }
}

// A codemux that died without its exit handler leaves the file behind; it is
// swept only once older than any run could still be reading it.
const STALE_FILE_MS = 2 * 86_400_000;

/** Removes files left behind by codemux processes that no longer exist. */
function sweepStaleFiles(parent: string): void {
  let entries: string[];
  try {
    entries = readdirSync(parent);
  } catch {
    return;
  }
  for (const entry of entries) {
    const match = /^no-tools-(\d+)-/.exec(entry);
    if (!match) continue;
    const pid = Number(match[1]);
    if (pid === process.pid || processAlive(pid)) continue;
    const path = join(parent, entry);
    let age: number;
    try {
      age = Date.now() - statSync(path).mtimeMs;
    } catch {
      continue;
    }
    if (age < STALE_FILE_MS) continue;
    rmSync(path, { force: true });
  }
}

/**
 * Writes the no-tools agent file. `brandHome` is the real kimi brand home
 * (the directory `kimi` reads config.toml, skills and agents from).
 */
export function writeKimiNoToolsFile(brandHome: string): KimiNoToolsFile {
  const parent = join(brandHome, PARENT_DIR_NAME);
  mkdirSync(parent, { recursive: true, mode: 0o700 });
  // A run with write access to the brand home could have replaced the parent
  // with a symlink, pointing the sweep's rm elsewhere.
  const parentStat = lstatSync(parent);
  if (
    !parentStat.isDirectory() ||
    (process.platform !== "win32" &&
      typeof process.getuid === "function" &&
      parentStat.uid !== process.getuid())
  ) {
    throw new Error(`${parent} must be a directory owned by the current user`);
  }
  sweepStaleFiles(parent);
  const path = join(parent, `${FILE_PREFIX}${process.pid}-${randomBytes(6).toString("hex")}.md`);
  writeFileSync(path, AGENT_FILE_TEXT, { mode: 0o600 });

  let finalized = false;
  const finalize = (): void => {
    if (finalized) return;
    finalized = true;
    rmSync(path, { force: true });
    process.off("exit", finalize);
  };
  process.once("exit", finalize);

  return { path, finalize };
}
